<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ShipWalk.Tests</AssemblyName>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <GameRoot Condition="'$(GameRoot)' == ''">$(MSBuildThisFileDirectory)..\..\..\</GameRoot>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\src\ShipWalk.csproj" />
    <Reference Include="System.Numerics" />
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameRoot)Client\Empyrion_Data\Managed\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
